version: '3.1'

services:
  adminer:
    image: thedifferent/adminer-alpine
    #build: adminer/latest
    networks:
      - "adminer"
      - "traefik"
    ports:
      - "${AD_PORT}:8888"

networks:
  adminer:
    external:
      name: adminer-net

  traefik:
    external:
      name: traefik-net
