version: '3.1'

services:
  adminer:
    image: thedifferent/adminer-alpine
    #build: adminer/latest
    networks:
      - "proxy-net"
    ports:
      - "${AD_PORT}:8888"

networks:
  proxy-net:
    external:
      name: ${AD_NW}
