version: '3.1'

services:
  adminer:
    image: thedifferent/adminer-alpine
    #build: adminer/latest
    networks:
      - "dbgui"
      - "rvproxy"
    ports:
      - "${AD_PORT}:8888"

networks:
  dbgui:
    external:
      name: adminer-net

  rvproxy:
    external:
      name: traefik-net
