version: '3.1'

services:
  adminer:
    image: thedifferent/adminer-alpine
    #build: adminer/latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=8888"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${TRAEFIK_FR_Host}"
        - "traefik.backend=${DOCKERCLOUD_CONTAINER_HOSTNAME}"
    networks:
      - "dbgui"
      - "rvproxy"

networks:
  dbgui:
    external:
      name: adminer-net
  rvproxy:
    external:
      name: traefik-net
